[Interface]
PrivateKey = UFc8yH9MWmE7ONNnX4iL7/hw1tLM7dJabjFPDwukYXM=
Address = 10.0.0.3/24
DNS = 8.8.8.8, 8.8.4.4

[Peer]
PublicKey = PBhKD8K+EtXNMLslkSxgST2yl/gCcKZWVyD1dS/0pBI=
AllowedIPs = 0.0.0.0/0
Endpoint = 157.151.255.127:51820
