# Generated by Django 5.2.13 on 2026-04-30 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AsientoContable',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('Fecha', models.DateField()),
                ('Debe', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('Haber', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('Comentarios', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Asiento contable',
                'verbose_name_plural': 'Asientos contables',
                'db_table': 'AsientosContables',
                'ordering': ['-Fecha'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('ID_Bitacora', models.BigAutoField(primary_key=True, serialize=False)),
                ('Fecha_Hora', models.DateTimeField(auto_now_add=True)),
                ('Usuario', models.CharField(max_length=100)),
                ('Tabla', models.CharField(max_length=50)),
                ('Operacion', models.CharField(choices=[('INSERT', 'INSERT'), ('UPDATE', 'UPDATE'), ('DELETE', 'DELETE')], max_length=10)),
                ('Registro_Clave', models.CharField(max_length=100)),
                ('Detalle', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Entrada de bitácora',
                'verbose_name_plural': 'Bitácora de auditoría',
                'db_table': 'Bitacora',
                'ordering': ['-Fecha_Hora'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CatalogoCuenta',
            fields=[
                ('ID_Cuenta', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=150)),
                ('Tipo', models.CharField(choices=[('Activo', 'Activo'), ('Pasivo', 'Pasivo'), ('Patrimonio', 'Patrimonio'), ('Ingreso', 'Ingreso'), ('Gasto', 'Gasto'), ('Costo', 'Costo')], max_length=15)),
                ('Activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Cuenta contable',
                'verbose_name_plural': 'Catálogo de cuentas',
                'db_table': 'CatalogoCuentas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('Telefono', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=150)),
                ('Direccion', models.CharField(max_length=255)),
                ('Correo', models.CharField(blank=True, max_length=120, null=True)),
                ('NIT', models.CharField(default='CF', max_length=20)),
                ('Fecha_Alta', models.DateField()),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'Clientes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('ID_Pedido', models.BigAutoField(primary_key=True, serialize=False)),
                ('Fecha', models.DateField()),
                ('Total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('Estado', models.CharField(choices=[('Pendiente de Pago', 'Pendiente de Pago'), ('Pagado', 'Pagado'), ('Anulado', 'Anulado')], default='Pendiente de Pago', max_length=30)),
                ('Pago', models.CharField(choices=[('Efectivo', 'Efectivo'), ('Transferencia', 'Transferencia'), ('Tarjeta', 'Tarjeta')], max_length=20)),
                ('Envio', models.CharField(blank=True, max_length=100, null=True)),
                ('Entregado', models.BooleanField(default=False)),
                ('Creado_En', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'db_table': 'Pedidos',
                'ordering': ['-Fecha', '-ID_Pedido'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InventarioHistorico',
            fields=[
                ('Fecha', models.DateField(primary_key=True, serialize=False)),
                ('Peso', models.DecimalField(decimal_places=3, max_digits=10)),
            ],
            options={
                'verbose_name': 'Inventario histórico',
                'verbose_name_plural': 'Inventario histórico',
                'db_table': 'InventarioHistorico',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('ID_Movimiento', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('Fecha', models.DateField()),
                ('Debe', models.FloatField(blank=True, null=True)),
                ('Haber', models.FloatField(blank=True, null=True)),
                ('Comentario', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Movimiento de inventario',
                'verbose_name_plural': 'Movimientos de inventario',
                'db_table': 'MovimientosInventario',
                'ordering': ['-Fecha'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('SKU', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Producto', models.CharField(max_length=120)),
                ('Precio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Stock_Minimo', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('Activo', models.BooleanField(default=True)),
                ('Fecha_Alta', models.DateField()),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'Productos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VwFacturaCompleta',
            fields=[
                ('ID_Pedido', models.BigIntegerField(primary_key=True, serialize=False)),
                ('Fecha', models.DateField()),
                ('Estado', models.CharField(max_length=30)),
                ('Pago', models.CharField(max_length=20)),
                ('Envio', models.CharField(blank=True, max_length=100, null=True)),
                ('Entregado', models.BooleanField()),
                ('Total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('Nombre_Cliente', models.CharField(max_length=150)),
                ('Telefono_Cliente', models.CharField(max_length=20)),
                ('NIT', models.CharField(max_length=20)),
                ('Direccion', models.CharField(max_length=255)),
                ('SKU', models.CharField(max_length=20)),
                ('Producto', models.CharField(max_length=120)),
                ('Cantidad', models.IntegerField(blank=True, null=True)),
                ('Peso', models.FloatField()),
                ('Precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Descuento', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'verbose_name': 'Factura completa',
                'db_table': 'vw_FacturaCompleta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VwPendienteDeEntrega',
            fields=[
                ('ID_Pedido', models.BigIntegerField(primary_key=True, serialize=False)),
                ('Fecha', models.DateField()),
                ('Cliente', models.CharField(max_length=150)),
                ('Telefono', models.CharField(max_length=20)),
                ('Direccion', models.CharField(max_length=255)),
                ('Total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('Envio', models.CharField(blank=True, max_length=100, null=True)),
                ('Peso_Total_lb', models.FloatField()),
            ],
            options={
                'verbose_name': 'Pendiente de entrega',
                'db_table': 'vw_PendientesDeEntrega',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VwPendienteDePago',
            fields=[
                ('ID_Pedido', models.BigIntegerField(primary_key=True, serialize=False)),
                ('Fecha', models.DateField()),
                ('Dias_Vencimiento', models.IntegerField()),
                ('Cliente', models.CharField(max_length=150)),
                ('Telefono', models.CharField(max_length=20)),
                ('Total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('Pago', models.CharField(max_length=20)),
                ('Envio', models.CharField(blank=True, max_length=100, null=True)),
                ('Entregado', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Pendiente de pago',
                'db_table': 'vw_PendientesDePago',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VwStockActual',
            fields=[
                ('SKU', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Producto', models.CharField(max_length=120)),
                ('Stock_Minimo', models.DecimalField(decimal_places=3, max_digits=10)),
                ('Ingresos_lb', models.FloatField()),
                ('Transf_Salida_lb', models.FloatField()),
                ('Ventas_lb', models.FloatField()),
                ('Stock_lb', models.FloatField()),
                ('Estado_Stock', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Stock actual',
                'db_table': 'vw_StockActual',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VwVentaPorCliente',
            fields=[
                ('Telefono', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=150)),
                ('NIT', models.CharField(max_length=20)),
                ('Num_Pedidos', models.IntegerField()),
                ('Total_Comprado_Q', models.DecimalField(decimal_places=2, max_digits=12)),
                ('Deuda_Q', models.DecimalField(decimal_places=2, max_digits=12)),
                ('Ultima_Compra', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Ventas por cliente',
                'db_table': 'vw_VentasPorCliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VwVentaPorFecha',
            fields=[
                ('Fecha', models.DateField(primary_key=True, serialize=False)),
                ('Num_Pedidos', models.IntegerField()),
                ('Total_Q', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'verbose_name': 'Ventas por fecha',
                'db_table': 'vw_VentasPorFecha',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VwVentaPorProducto',
            fields=[
                ('SKU', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Producto', models.CharField(max_length=120)),
                ('Num_Pedidos', models.IntegerField()),
                ('Peso_Total_lb', models.FloatField()),
                ('Total_Q', models.DecimalField(decimal_places=2, max_digits=12)),
                ('Precio_Promedio', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Ventas por producto',
                'db_table': 'vw_VentasPorProducto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('ID_Pedido', models.ForeignKey(db_column='ID_Pedido', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='detalles', serialize=False, to='core.pedido')),
                ('Cantidad', models.IntegerField(blank=True, null=True)),
                ('Peso', models.FloatField()),
                ('Precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Descuento', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('Subtotal', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
            ],
            options={
                'verbose_name': 'Línea de pedido',
                'verbose_name_plural': 'Detalle de pedidos',
                'db_table': 'DetallePedido',
                'managed': False,
            },
        ),
    ]
